### ISSUE TITLE
Class's items

### ISSUE THREAD

**Issue by Tych0n** [alkarinv/BattleArena#102]
Hello, I have a problem. How things should work: player taps the 'join' sign and his inventory saves and wipes, then he taps 'class' sign (gladiator in example) and he is given preset stuff, then he is teleported to arena with that stuff, when he leaves his inventory wipes nad restores from the saved items. How they actually works: when player taps 'join' sign his inventory saves (in inventory/Player.yml everything is ok) but not wipes, when he taps 'class' sign his inventory wipes and he is given preset stuff, then he is teleported to the arena with empty inventory, when he leaves he is given not his saved inventory but the preset stuff of his class. My config is default with simple 'arena' with 1 spawn. 

```
onEnter:
    options: [storeAll]
onLeave:
    options: [restoreAll]
onStart:
    options: [teleportIn]
onSpawn:
    options: []
    giveClass:
        default: chosenClass
```
