### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by justicets** [alkarinv/BattleArena#121]
I have been looking, but can't figure out the permissions, only ops can join a game.
Can someone please tell me what I should hcange so anyone can join?

Just

**Comment by darrenstraight** [comment]
Did you look at: https://github.com/alkarinv/BattleArena/wiki/Permissions

What permissions system you using?

**Comment by justicets** [comment]
permissionex I pasted in to permissions.yml and doesnt seem to make a difference.

groups:
  default:
    default: true
    permissions:

  children:
    arena.arena.join: true
    arena.skirmish.join: true
    arena.bg.join: true
    arena.col.join: true
    arena.tourney.join: true
    arena.ffa.join: true
    arena.dm.join: true

```
   - modifyworld.*
```

**Comment by alkarinv** [comment]
So you can't just paste into the permissions.yml.  That is if you are using default bukkit perms.

What you need to do is open up the plugins/PermissionsEx/permissions.yml

Add them into the default group there

**Comment by darrenstraight** [comment]
Here's an example of my PermissionsEx file, I've taken away all the permissions not relevant to BattleArena, however I've left the group name and prefix colour. You could just take options out and prefix and of course change "Member" to what ever you want your default group to be called. It should work no problems, more info on correct permissions formatting on permissions ex setup: https://github.com/PEXPlugins/PermissionsEx/wiki/Basic-Permissions-Setup

```
groups:
    Member:
        default: true
        prefix: '&7'
        options:
            rank: '600'
            build: true
        permissions:
        - arena.arena.join
        - arena.skirmish.join
        - arena.bg.join
        - arena.col.join
        - arena.tourney.join
        - arena.ffa.join
        - arena.dm.join
```
