### ISSUE TITLE
Can't prevent users from stealing

### ISSUE THREAD

**Issue by Koocachookies** [alkarinv/BattleArena#201]
I have a Craftbukkit Server with a normal map called "world" and a special map called "eventos". In this world I have a lot of games like mobarena, spleef and, of course, battlearena-based games. 

The players use the commands to join these arenas and then they are teleported to the waitroom where they select the class they want to play. The problem comes when they use commands like home or spawn. They teleport to their homes and steal all the equipment of the selected class placing it in a chest. I've tried using the "disabledQueueCommands" option at the config.yml file and and placing the "noTeleport" and "noWorldChange" options at the defaults, onJoin, onOpen or onPrestart stages from the <arena>config.yml file but none of them are working. What can I do?

This is an amazing plugin but if I'm not able to fix this issue I think I will have to discard it :(

**Comment by cust0dian-old** [comment]
@Koocachookies I had similar issue and it was resolved by adding `noTeleport` to `onJoin`. 

Can you post your current configs for a competitions that aren't working correctly `/plugins/BattleArena/competitions/YourCompetitionConfig.yml`?

**Comment by Koocachookies** [comment]
This is the last config I've used.

CaptureTheFlag:
    queue: false
    type: CaptureTheFlag
    prefix: "&8[CTF]&e"
    command: ctf
    rated: true
    database: ctf 
    matchTime: 600 
    joinType: joinPhase 
    victoryCondition: HighestKills
    nLives: infinite
    nTeams: 2
    teamSize: 1+
    secondsTillBegin: 15
    secondsTillMatch: 5 
    matchTime: 600 
    matchUpdateInterval: 15 
    defaults: 
        options: [woolTeams, alwaysTeamNames, hunger=20, dropItemOff]
    preReqs: 
        options: [wgNoEnter, wgNoLeave]
    onEnter:
        options: [storeAll]
    onLeave:
        options: [restoreAll]
    onJoin:
        options: [teleportWaitRoom, pvpOff, noWorldChange, noTeleport]
    onOpen:
        options: [pvpOff, noWorldChange, noTeleport]
    onPrestart:
        options: [pvpOff, deEnchant, noWorldChange, noTeleport]
        giveClass:
            default: acorazado
    onStart:
        options: [pvpOn, teleportIn, hunger=20]
    onComplete: 
        options: [teleportOut]
    onFinish: 
        options: []
    onSpawn:
        options: [health=20, hunger=20, respawnWithClass]
    onDeath:
        options: [clearInventory, respawn]
    winner:
        options: [health=20, hunger=20, money=500, experience=170]

**Comment by cust0dian-old** [comment]
@Koocachookies can you include ````yaml` before the code and ````` after the code? Whitespace is important with YAML. :smiley: 

It should look something like this:

``````
```yaml
CaptureTheFlag:
    queue: true
    type: CaptureTheFlag
    prefix: "&8[CTF]&e"
    command: ctf
    ...
```
``````

**Comment by Koocachookies** [comment]
I've tried what you said before and it keeps on allowing teleport.

``` yaml
CaptureTheFlag:
    queue: false
    type: CaptureTheFlag
    prefix: "&8[CTF]&e"
    command: ctf
    rated: true
    database: ctf # or delete if you dont want wins/losses/top, needs BattleTracker
    matchTime: 600 # in seconds
    joinType: joinPhase ## Queue or JoinPhase
    victoryCondition: HighestKills
    nLives: infinite
    nTeams: 2
    teamSize: 1+
    secondsTillBegin: 15
    secondsTillMatch: 5 ## how long between onPrestart and onStart
    matchTime: 600 ## How long do timed matches last, (in seconds)
    matchUpdateInterval: 15 ## For timed matched, how long between sending players match updates
    defaults: ## Global options for the entire match
        options: [woolTeams, alwaysTeamNames, hunger=20, dropItemOff]
    preReqs: ## requirements to join
        options: [wgNoEnter, wgNoLeave]
    onEnter:
        options: [storeAll]
    onLeave:
        options: [restoreAll]
    onJoin:
        options: [teleportWaitRoom, pvpOff, noWorldChange, noTeleport]
    onOpen:
        options: [pvpOff]
    onPrestart:
        options: [pvpOff, deEnchant]
        giveClass:
            default: acorazado
    onStart:
        options: [pvpOn, teleportIn, hunger=20]
    onComplete: ## Called when a player leaves, or no longer is supposed to spawn in arena
        options: [teleportOut]
    onFinish: ### effects after game is finished
        options: []
    onSpawn:
        options: [health=20, hunger=20, respawnWithClass]
    onDeath:
        options: [clearInventory, respawn]
    winner:
        options: [health=20, hunger=20]
```
