### ISSUE TITLE
Custom Classes Not Working?

### ISSUE THREAD

**Issue by gm4n22** [alkarinv/BattleArena#303]
I create the custom class in the config but then it does not recognize the class? Plz help

**Comment by daugvydas120** [comment]
the dev isn't active anymore

**Comment by creptor** [comment]
why don't you post your config? http://pastebin.com

**Comment by arsenalfcgunners** [comment]
This won't work for me.  I don't understand why. http://pastebin.com/zrxZg9bH

**Comment by Europia79** [comment]
@arsenalfcgunners 

looks like incorrect yaml formatting for a list:

``` yaml
classes:
    gladiator:
        displayName: "&4Gladiator" ### Used for signs
        items:
        - iron_sword: 1
        - bow: 1
        - arrow: 16
        - iron_helm: 1
        - iron_chest: 1
        - iron_leggings: 1
        - iron_boots: 1
        - fishing_rod: 1
```
