### ISSUE TITLE
How do you add prices to classes 

### ISSUE THREAD

**Issue by zmw1234** [alkarinv/BattleArena#309]
Some one please help. How can i make so each class has a set price to buy.

**Comment by Europia79** [comment]
use the doCommands to charge players.

edit /plugins/BattleArena/classes.yml

Here's an example:

``` yaml
classes:
    Vector:
        displayName: "&1Vector"
        items:
            - 2256: 1 # record_13.png
            - 2257: 1 # Colt Handgun - record_cat.png
            - 402: 2 # M67 Grenades
            - 345: 1 # Compass for directions
            - 295: 64 # Ammo = Seeds
            - 295: 64 # Ammo = Seeds
        enchants:
            - speed:2:900
        doCommands:
            - console money take player 100
```

Except substitute `money take` with the equivalent command of your economy plugin.
And substitute `100` with the actual amount that you want to charge.

`console` means that the cmd will be run as the console CommandSender.
`player` will be replaced with the player selecting the class.

**Comment by zmw1234** [comment]
How would i make it check to see if the player has enough money ? what if they have less then the amount i dont want them to be able to have the class if they do.

**Comment by zmw1234** [comment]
also what do i put for the docommand

**Comment by Europia79** [comment]
Good point about not having enough money... That will have to be fixed.
I'll have to add either a 'cost' or 'preReqs' section... And maybe a refund section too... So servers can configure the refund amount if a player switches classes. (either full, partial, or none - specified by amount).

As far as the specific command to take money: I'm not sure. It would probably depend on what economy plugin that you're using. The general form would be this:
`console money take player 100`

Here are some possible future options:

``` yaml
classes:
    Vector:
        displayName: "&1Vector"
        items:
            - 2256: 1 # record_13.png
            - 2257: 1 # Colt Handgun - record_cat.png
            - 402: 2 # M67 Grenades
            - 345: 1 # Compass for directions
            - 295: 64 # Ammo = Seeds
            - 295: 64 # Ammo = Seeds
        enchants:
            - speed:2:900
        doCommands:
            - console money take player 100
        preReqs:
            options: [money=100]
        cost: 100
        refund: 90
```

What do you think ?
